version: "3"

services:
  mysql:
    image: mariadb:5.5
    volumes:
      - "./db/mysql:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - "./db/mssql:/var/opt/mssql:rw"
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=${SA_PASSWORD}"
    ports:
      - "1433:1433"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/db/postgres-init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432
